### ISSUE TITLE
cmke status returning one : Shadow tor

### ISSUE THREAD

**Issue by kunalsutradhar13** [shadow/shadow-plugin-tor#10]
i downloaded the shadow setup file, then as i try to build it, this is what i get...

derpina@derpina-Dell-System-XPS-L502X:~/shadow$ ./setup build
2015-02-14 07:27:10,487 INFO running 'cmake /home/derpina/shadow -DCMAKE_INSTALL_PREFIX=/home/derpina/.shadow -DCMAKE_EXTRA_INCLUDES=/home/derpina/shadow/build/shadow;/home/derpina/.shadow/include -DCMAKE_EXTRA_LIBRARIES=/home/derpina/shadow/build/shadow;/home/derpina/.shadow/lib' from '/home/derpina/shadow/build/shadow'
-- 
-- -------------------------------------------------------------------------------
-- Current settings: (change with '$ cmake -D<OPTION>=<ON|OFF>')
-- SHADOW_DEBUG=OFF
-- SHADOW_PROFILE=OFF
-- SHADOW_TEST=OFF
-- SHADOW_EXPORT=OFF
-- -------------------------------------------------------------------------------
-- 
-- CMAKE_BUILD_TYPE Release enabled.
-- CMAKE_MODULE_PATH = /home/derpina/shadow/cmake/;/home/derpina/.shadow/include;/home/derpina/shadow/build/shadow
-- Found components for RT
-- RT_INCLUDES = /usr/include
-- RT_LIBRARIES = /usr/lib/i386-linux-gnu/librt.so
-- Found components for DL
-- DL_INCLUDES = /usr/include
-- DL_LIBRARIES = /usr/lib/i386-linux-gnu/libdl.so
-- Found components for M
-- M_INCLUDES = /usr/include
-- M_LIBRARIES = /usr/lib/i386-linux-gnu/libm.so
-- Found components for IGRAPH
-- IGRAPH_INCLUDES = /usr/include/igraph
-- IGRAPH_LIBRARIES = /usr/lib/i386-linux-gnu/libigraph.so
-- Found components for GLIB
-- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/lib/i386-linux-gnu/glib-2.0/include
-- GLIB_LIBRARIES = /usr/lib/i386-linux-gnu/libglib-2.0.so;/usr/lib/i386-linux-gnu/libgthread-2.0.so;/usr/lib/i386-linux-gnu/libgmodule-2.0.so
-- Checking for C LLVM compiler...
-- Checking for C LLVM compiler... works.
-- Checking for CXX LLVM compiler...
-- Checking for CXX LLVM compiler... works.
CMake Error at cmake/FindLLVM.cmake:33 (message):
  Unable to find path to LLVM Config file LLVM-Config.cmake
Call Stack (most recent call first):
  src/plugin/llvm-hoist-pass/CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
2015-02-14 07:27:10,714 INFO cmake returned 1
2015-02-14 07:27:10,714 ERROR  Non-zero return code from cmake.
2015-02-14 07:27:10,714 INFO returning code '1'

can some please help me out here...

**Comment by robgjansen** [comment]
First of all, you are trying to build shadow and not tor, so this does not belong on the Tor wiki. Secondly, this is a setup issue and not a bug. Please mail future support problems to shadow-support@cs.umn.edu for help with setup problems.

It looks like your LLVM installation is missing the `LLVM-Config.cmake` file, or you have not included the path to it using the `--include` option of the setup.py script. See more here:
https://github.com/shadow/shadow/wiki/4-Notes-and-FAQs#my-os-does-not-include-the-correct-clangllvm-cmake-modules-how-do-i-build-clangllvm-from-source
