### ISSUE TITLE
mini example for shadow-plugin-tor log question

### ISSUE THREAD

**Issue by GitZinger** [shadow/shadow-plugin-tor#102]
question:
https://github.com/shadow/shadow-plugin-tor/wiki#Running%20Tor%20in%20Shadow
and this one too
https://github.com/shadow/shadow/blob/master/docs/2-Getting-Started-Tutorial.md#Basic%20functional%20tests

the run command is
`shadow shadow.config.xml > shadow.log`
afterwards, the information goes into **shadow.log** and **client-transfers-complete.log**?
but in the following instructions:
`for d in shadow.data/hosts/*client*; do grep "stream-success" ${d}/* ; done | tee clients.log | wc -l
`the clients.log 
should be replaced with **shadow.log** or **client-transfers-complete.log** or something?
and **shadow.data/hosts/** is it correct? it prompts that it is a directory or something in my end?
I am new to here! I really appreciate your advise!

**Comment by robgjansen** [comment]
`shadow.log` contains the log output from shadow.

There is log file for each process that is run on a host. Those are stored in host-specific directories in `shadow.data/hosts/*/`.

This command searches through the tgen log files and counts the number of successful streams.

```
for d in shadow.data/hosts/*client*; do grep "stream-success" ${d}/*tgen*log ; done | wc -l
```
