### ISSUE TITLE
what is the relation among shadow, Tor and TGen working together?

### ISSUE THREAD

**Issue by GitZinger** [shadow/shadow-plugin-tor#103]
My guess the Shadow is the base environment. But how do Tor and TGen work together? the traffic were generated by TGen, and they are received by Tor as the application in the client end?
Thank you so much!

**Comment by robgjansen** [comment]
Shadow is the base network simulation environment. TGen and Tor are applications that normally run over the internet, but in our case are running over the simulated network in Shadow.

The virtual hosts that are running TGen processes also run Tor clients. The Tor client runs a SOCKS proxy server that listens on locahost, and TGen generates traffic and sends it to this SOCKS proxy server on localhost. That gets the traffic from TGen to Tor. The Tor client builds 3-hop Tor circuits, and forwards the TGen requests to TGen servers that are also running in the simulation. Then data can be sent back and forth from the TGen server and TGen client through the Tor circuit.

You should read more about how Tor works from the [Tor website](https://www.torproject.org/), [Tor support page](https://support.torproject.org/), and [Tor documentation page](https://2019.www.torproject.org/docs/documentation.html.en).

**Comment by GitZinger** [comment]
> Shadow is the base network simulation environment. TGen and Tor are applications that normally run over the internet, but in our case are running over the simulated network in Shadow.
> 
> The virtual hosts that are running TGen processes also run Tor clients. The Tor client runs a SOCKS proxy server that listens on locahost, and TGen generates traffic and sends it to this SOCKS proxy server on localhost. That gets the traffic from TGen to Tor. The Tor client builds 3-hop Tor circuits, and forwards the TGen requests to TGen servers that are also running in the simulation. Then data can be sent back and forth from the TGen server and TGen client through the Tor circuit.
> 
> You should read more about how Tor works from the [Tor website](https://www.torproject.org/), [Tor support page](https://support.torproject.org/), and [Tor documentation page](https://2019.www.torproject.org/docs/documentation.html.en).

My understanding is that Shadow works as OSI network layer 3- layer4. and Tor-plug-in works as layer 5- layer 7. However we don't have users in there. So we use the TGen to simulate the whole traffic. Am I on the right track?

**Comment by robgjansen** [comment]
Yes, that's a good way to think about it.
