### ISSUE TITLE
about shadowtor-minimal-config test

### ISSUE THREAD

**Issue by suzy520** [shadow/shadow-plugin-tor#105]
May I ask why I deleted the shadow.data.template in the shadowtor-minimal-config and the experiment did not run successfully, and the one that did not delete can run successfully. What is the principle? I have just been in contact with the shadow. I do n’t know why.

**Comment by robgjansen** [comment]
The template directory is used as the starting point for each new simulation. It contains relay fingerprints and key material that is needed to bootstrap the network.
