### ISSUE TITLE
Misconfigured graphml scripts

### ISSUE THREAD

**Issue by jmartinhoj** [shadow/shadow-plugin-tor#107]
With the new release of tgen (1.0.0), it won't accept the "type" attribute in the hosts' configuration graphml file. As so, I recommend you to update your configuration files in the resources/ folder.

**Comment by jmartinhoj** [comment]
I solved the issue by downgrading to tgen 0.0.1.

**Comment by stevenengler** [comment]
Duplicate of #100.
