### ISSUE TITLE
Using Shadow and Tor Plugin while developing alternative Tor client

### ISSUE THREAD

**Issue by mdccxv** [shadow/shadow-plugin-tor#108]
I am planning to develop an alternative Tor client, more as a discardable prototype and a way to deepen knowledge about onion routing. I am currently looking for tools that would support my effort.
Now, I see that Shadow coupled with Tor Plugin allow to simulate a complex Tor network running various experiments, yet it is not clear to me if I can somehow interface with the simulated network from the external application. In other words, if I start to develop a program that would be essentially a Tor relay node, can I use Shadow Tor to test it?

**Comment by jtracey** [comment]
See the documentation on [shadow plugins](https://github.com/shadow/shadow/blob/master/docs/2-Getting-Started-Tutorial.md#shadow-plug-ins). If your client is written in C or C++, it should be fairly straightforward to get it working with shadow; if it's in another language, it would be possible but likely very difficult to do.

**Comment by robgjansen** [comment]
See also shadow/shadow#764 for my answer to a related question about using Shadow for mixnets.

**Comment by robgjansen** [comment]
> @robgjansen do you think that this future Shadow v2 that you mention in another thread would make it any easier to interface with it?

Yes, absolutely Shadow v2 will make it easier to run applications written in languages other than C/C++. I don't yet have a solid timeframe for when v2 will be ready. It likely won't be **stable** for a few months, but I think we'll have a **buggy** version out sooner than that which you could play with at your own risk :)

**Comment by robgjansen** [comment]
Shadow v2 development is taking place in [the dev branch on the main shadow repo](https://github.com/shadow/shadow/tree/dev) if you want to follow along. (It's still not considered stable at this point, but we are making good progress!)
