### ISSUE TITLE
Addition of deterministic nodes to model network from tornetgen

### ISSUE THREAD

**Issue by rxcomm** [shadow/shadow-plugin-tor#111]
I have a question about using shadow-plugin-tor to model tor
network behavior. To this point, I've used tornetgen successfully to
build a network model that I have run in shadow. This works great.

What I would like to do, is to add one or
more node pairs to the tornetgen model network that emit (and
consume) plaintext packets of a constant size at a constant rate.
These would be transferred into the model tor network through a socks
proxy. The consumer would be a hidden service.

An example application using this kind of packet model might be e.g. a
telemetry application. Typical numbers I am interested in modeling
are of the order of e.g. 1kB of plaintext data per 10 ms.

How do I go about achieving this? Thanks in advance.

**Comment by robgjansen** [comment]
Assuming you just want to model the traffic flows (and not actually support some real application), then this is pretty easy using TGen.

You'll need some pieces to make it work:

1. Add a "client" and "server" host to the generated `shadow.config.xml`. Just doing this by hand is probably the easiest to start with. Use the existing hosts as an example of the attributes you'll want to set.
1. I think both the client and the server will want a Tor `process` configured, as well as a `tgen` process to do the actual data transfer. You'll want to run the server Tor in hidden service mode, and the client Tor in client mode. Examples of hidden server clients and servers are inside of the ["minimal" example](https://github.com/shadow/shadow-plugin-tor/blob/master/resource/shadowtor-minimal-config.tar.xz), so I would copy-paste from there.
1. Once you have all of that set up, then you can tweak the behavior of the `tgen` client process by changing the config file whose location you pass in the arguments field in the shadow config file. Building a new tgen model is simple but might be a little tricky at first. See [here](https://github.com/shadow/tgen/blob/master/doc/TGen-Overview.md) and [here](https://github.com/shadow/tgen/blob/master/doc/TGen-Options.md) and then ask questions if you have them.

Hope that helps get you started!

**Comment by rxcomm** [comment]
Thanks for this - I believe I've got it working now. A useful link for those following along at home that provides examples compatible with tgen 1.0.0 (the tgen API changed a bit):

https://github.com/shadow/shadow-plugin-tor/pull/101

Be sure to grab the graphml for the minimal example from here.
