### ISSUE TITLE
Running Tor in Shadow returns code -1 (error) 

### ISSUE THREAD

**Issue by pmicos** [shadow/shadow-plugin-tor#115]
Hi there,

While the 'Basic functional tests in Shadow' were executed successfully, now I'm following the shadow-plugin-tor wiki and I'm getting the same error every time I run Tor in Shadow. 

```
$ shadow -w 4 shadow.config.xml > shadow.log

** Starting Shadow v1.13.2-676-gd2fc305e 2021-02-02--10:26:23 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code -1 (error)
```
Looking for error messages inside shadow.log I found these 4 **log messages**:

`00:00:05.370566 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:428] [_process_loadPlugin] process 'torhiddenclient.tgen.1002' successfully loaded plugin 'tgen' at path '/home/mic/.shadow/bin/tgen' into new namespace '0x7f7df00fc010' in 0.010863 seconds

00:00:05.370585 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:495] [_process_loadPlugin] found 'main' at 0x7f7da4a90b30

00:00:05.370731 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:997] [_process_executeMain] calling main() for process 'torhiddenclient.tgen.1002'

00:00:05.372367 [thread-2] 00:20:00.000000000 [warning] [torhiddenclient~11.0.0.10] [process.c:966] [_process_logReturnCode] **main error code '1' for process 'torhiddenclient.tgen.1002**'

00:00:05.372372 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:880] [_process_executeCleanup] cleaning up process 'torhiddenclient.tgen.1002': aborting 0 auxiliary threads and calling 0 atexit functions

00:00:05.372386 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:1159] [_process_start] process 'torhiddenclient.tgen.1002' initialized the pth threading system in 0.000106 seconds, initialized the plugin namespace in 0.011022 seconds, and ran the pth main thread until it blocked in 0.001661 seconds

00:00:05.372392 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [process.c:1177] [_process_start] process 'torhiddenclient.tgen.1002' has completed or is otherwise no longer running

00:00:05.372406 [thread-2] 00:20:00.000000000 [message] [torhiddenclient~11.0.0.10] [tracker.c:457] [_tracker_logNode] [shadow-heartbeat] [node] 
1,0,0,0.001629,0,0.000000;2,146,1,66,0,0,1,66,14,0,0,0;2,146,1,66,0,0,1,66,14,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0

00:00:05.372689 [thread-2] 00:20:00.000000000 [message] [torclient~11.0.0.9] [process.c:1063] [_process_start] starting process 'torclient.tgen.1002'

00:00:05.372817 [thread-0] 00:20:00.000000000 [warning] [torbridgeclient~11.0.0.11] [process.c:966] [_process_logReturnCode] **main error code '1' for process 'torbridgeclient.tgen.1002'**

00:00:05.372821 [thread-0] 00:20:00.000000000 [message] [torbridgeclient~11.0.0.11] [process.c:880] [_process_executeCleanup] cleaning up process 'torbridgeclient.tgen.1002': aborting 0 auxiliary threads and calling 0 atexit functions
`
...

`
00:00:05.383466 [thread-2] 00:20:00.000000000 [message] [torclient~11.0.0.9] [process.c:428] [_process_loadPlugin] process 'torclient.tgen.1002' successfully loaded plugin 'tgen' at path '/home/mic/.shadow/bin/tgen' into new namespace '0x7f7df0083150' in 0.010646 seconds

00:00:05.383472 [thread-3] 00:20:00.000000000 [message] [client~11.0.0.8] [process.c:997] [_process_executeMain] calling main() for process 'client.tgen.1000'

00:00:05.383487 [thread-2] 00:20:00.000000000 [message] [torclient~11.0.0.9] [process.c:495] [_process_loadPlugin] found 'main' at 0x7f7d94186b30

00:00:05.383629 [thread-2] 00:20:00.000000000 [message] [torclient~11.0.0.9] [process.c:997] [_process_executeMain] calling main() for process 'torclient.tgen.1002'

00:00:05.384367 [thread-3] 00:20:00.000000000 [warning] [client~11.0.0.8] [process.c:966] [_process_logReturnCode] **main error code '1' for process 'client.tgen.1000**'

00:00:05.384369 [thread-3] 00:20:00.000000000 [message] [client~11.0.0.8] [process.c:880] [_process_executeCleanup] cleaning up process 'client.tgen.1000': aborting 0 auxiliary threads and calling 0 atexit functions

00:00:05.384379 [thread-3] 00:20:00.000000000 [message] [client~11.0.0.8] [process.c:1159] [_process_start] process 'client.tgen.1000' initialized the pth threading system in 0.000073 seconds, initialized the plugin namespace in 0.014194 seconds, and ran the pth main thread until it blocked in 0.000913 seconds

00:00:05.384382 [thread-3] 00:20:00.000000000 [message] [client~11.0.0.8] [process.c:1177] [_process_start] process 'client.tgen.1000' has completed or is otherwise no longer running

00:00:05.384392 [thread-2] 00:20:00.000000000 [warning] [torclient~11.0.0.9] [process.c:966] [_process_logReturnCode] **main error code '1' for process 'torclient.tgen.1002**'

00:00:05.384392 [thread-3] 00:20:00.000000000 [message] [client~11.0.0.8] [tracker.c:457] [_tracker_logNode] [shadow-heartbeat] [node] 1,0,0,0.000891,0,0.000000;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0

00:00:05.384394 [thread-2] 00:20:00.000000000 [message] [torclient~11.0.0.9] [process.c:880] [_process_executeCleanup] cleaning up process 'torclient.tgen.1002': aborting 0 auxiliary threads and calling 0 atexit functions
`

I'm sure I've done something wrong, but I followed the wiki tutorial step by step and I can't find any solution.

I hope I've explained myself clearly considering my ignorance.

Thank you in advance.

**Comment by robgjansen** [comment]
I think you may have run into a tgen bug. There is a pull request open in #101 that provides a work-around. Can you see if the config provided in #101 fixes the issue for you, and please report what you find?

**Comment by pmicos** [comment]
Instead of cloning **shadow-plugin-tor** with:

`git clone https://github.com/shadow/shadow-plugin-tor.git`


I cloned with this one:

`git clone https://github.com/robgjansen/shadow-plugin-tor.git -b example-fixup`

Now it's working fine

`** Starting Shadow v1.13.2-676-gd2fc305e 2021-02-02--10:26:23 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)`

Thanks!!

**Comment by robgjansen** [comment]
Great, thanks for reporting!
