### ISSUE TITLE
Priority Experiment: " main error code '-1' for process 'webclient1.tor.1000' "

### ISSUE THREAD

**Issue by pmicos** [shadow/shadow-plugin-tor#118]
I'm running the 'vanilla' and 'priority' experiments and while 'vanilla' executes successfully, 'priority' returns the code '-1' after a while.  

By looking the shadow.log file it looks like the error code is referring to the processes 'webclient[1-307].tor.1000': 

`00:07:34.498855 [thread-2] 00:15:05.000000001 [warning] [webclient1~11.0.0.14] [process.c:966] [_process_logReturnCode] main error code '-1' for process 'webclient1.tor.1000'`

`00:07:34.498866 [thread-2] 00:15:05.000000001 [message] [webclient1~11.0.0.14] [process.c:880] [_process_executeCleanup] cleaning up process 'webclient1.tor.1000': aborting 0 auxiliary threads and calling 0 atexit functions`

`00:07:34.498917 [thread-2] 00:15:05.000000001 [warning] [webclient1~11.0.0.14] [process.c:6331] [process_emu_pthread_getspecific] pthread_getspecific() is handled by pth but not implemented by shadow`

Any idea what am I doing wrong, and how can I solve it?

Thank you in advance.

**Comment by jtracey** [comment]
You'll want to look at the logs for that tor process, in `shadow.data/hosts/`.

**Comment by pmicos** [comment]
Looks like I didn't notice that I was running the two experiments at the same time, so different processes were running with the same data. Silly me!

`Jan 01 00:15:00.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.`

Thanks anyway for your help!

**Comment by robgjansen** [comment]
Yep! You can use Shadow's `--data-directory` option to make sure multiple simultaneous experiments are using separate directory spaces.
