### ISSUE TITLE
No such file or directory for 'initdata' on running shadow-tor executable

### ISSUE THREAD

**Issue by viggyprabhu** [shadow/shadow-plugin-tor#14]
Hi,

I am getting the following error when I run shadow-tor executable. I am running it on Ubuntu 14.04.
viggy@viggy-laptop:~/shadow-plugin-tor$ shadow-tor -i shadow.config.xml 
Traceback (most recent call last):
  File "/home/viggy/.shadow/bin/shadow-tor", line 132, in <module>
    main()
  File "/home/viggy/.shadow/bin/shadow-tor", line 48, in main
    reset(args.output)
  File "/home/viggy/.shadow/bin/shadow-tor", line 122, in reset
    shutil.copytree(output+"/initdata", output+"/data")
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/home/viggy/workspace/Tor_Research/test_bed/shadow-plugin-tor/initdata'

This error is fixed if I created a initdata directory manually.

viggy@viggy-laptop:~/shadow-plugin-tor$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty
viggy@viggy-laptop:~/shadow-plugin-tor$ uname -a
Linux viggy-laptop 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by robgjansen** [comment]
This is not a bug. You need to run your experiment from within one of the included experiment directories. For example:

```
cd shadow-plugin-tor/resource
tar xaf minimal.tar.xz
cd minimal
shadow-tor -y
```

This is explained on the wiki here:
https://github.com/shadow/shadow-plugin-tor/wiki#configuring-shadow-to-run-the-plug-in

Hope that helps!

**Comment by viggyprabhu** [comment]
Thanks for the quick reply. I tried running it from minimal and its works perfectly and finishes the simulation. Now only concern is I do not understand the xml and what the simulation is doing. Could you kindly point me to some documentation where I could understand the arguments in the xml and how I could try to simulate any custom scenario.Any off-hand notes are also ok, I can try to understand and come up with proper wiki page.

**Comment by robgjansen** [comment]
This is documented on the Shadow wiki:
https://github.com/shadow/shadow/wiki/3-Simulation-Customization

The Shadow wiki main page is also a good place to learn more:
https://github.com/shadow/shadow/wiki
