### ISSUE TITLE
Unknown CMake command "add_shadow_plugin"

### ISSUE THREAD

**Issue by dmS0Zq** [shadow/shadow-plugin-tor#23]
My apologies if this is a noobish problem that is not shadow-plugin-tor's fault. Please let me know if that's the case.

I followed the Quick auto setup instructions on [the wiki](https://github.com/shadow/shadow-plugin-tor/wiki). I'm doing this from a python2 virtualenv. Let me know if you need more information.

    make[1]: Leaving directory '/homes/user/src/shadow-plugin-tor/build/tor'
    2016-03-02 16:36:45,075 INFO detected tor version 0.2.7.6
    2016-03-02 16:36:45,080 INFO running 'cmake /homes/user/src/shadow-plugin-tor -DCMAKE_INSTALL_PREFIX=/homes/user/.shadow -DTOR_VERSION_A=0 -DTOR_VERSION_B=2 -DTOR_VERSION_C=7 -DTOR_VERSION_D=6 -DCMAKE_EXTRA_INCLUDES=/homes/user/src/shadow-plugin-tor/build/main;/homes/user/.shadow/include;/homes/user
    /.local/include;/homes/user/.local/share/llvm/cmake -DCMAKE_EXTRA_LIBRARIES=/homes/user/src/shadow-plugin-tor/build/main;/homes/user/.shadow/lib;/homes/user/.local/lib -DCMAKE_TOR_LIBRARIES=' from '/homes/user/src/shadow-plugin-tor/build/main'
    -- The C compiler identification is Clang 3.5.0
    -- The CXX compiler identification is Clang 3.5.0
    -- Check for working C compiler: /usr/bin/clang
    -- Check for working C compiler: /usr/bin/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/clang++
    -- Check for working CXX compiler: /usr/bin/clang++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Debug enabled. Setting '-DDEBUG' and '-g'.
    -- Check if the system is big endian
    -- Searching 16 bit integer
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of unsigned short
    -- Check size of unsigned short - done
    -- Using unsigned short
    -- Check if the system is big endian - little endian
    -- SHADOW_ROOT = /homes/user/.shadow
    -- CMAKE_INSTALL_PREFIX = /homes/user/.shadow
    -- CMAKE_PREFIX_PATH = /homes/user/.shadow
    -- CMAKE_MODULE_PATH = /homes/user/src/shadow-plugin-tor/cmake/;/homes/user/.shadow/share/cmake/Modules
    -- LLVMHoistGlobalsPATH = /homes/user/.shadow/lib/LLVMHoistGlobals.so
    -- Checking for C LLVM compiler...
    -- Checking for C LLVM compiler... works.
    -- Checking for CXX LLVM compiler...
    -- Checking for CXX LLVM compiler... works.
    -- CMAKE_C_FLAGS =  -g -fno-inline -fno-strict-aliasing
    -- Found ZLIB: /usr/lib64/libz.so (found version 1.2.8) 
    -- Found components for RT
    -- RT_INCLUDES = /usr/include
    -- RT_LIBRARIES = /usr/lib64/librt.so
    -- Found components for DL
    -- DL_INCLUDES = /usr/include
    -- DL_LIBRARIES = /usr/lib64/libdl.so
    -- Found components for M
    -- M_INCLUDES = /usr/include
    -- M_LIBRARIES = /usr/lib64/libm.so
    -- Found components for OPENSSL
    -- OPENSSL_INCLUDES = /homes/user/.shadow/include/openssl
    -- OPENSSL_LIBRARIES     = /homes/user/.shadow/lib/libssl.so;/homes/user/.shadow/lib/libcrypto.so
    -- Found components for EVENT2
    -- EVENT2_INCLUDES = /homes/user/.shadow/include
    -- EVENT2_LIBRARIES     = /homes/user/.shadow/lib/libevent.so;/homes/user/.shadow/lib/libevent_pthreads.so
    -- Found components for GLIB
    -- GLIB_INCLUDES = /usr/include/glib-2.0;/usr/lib/glib-2.0/include
    -- GLIB_LIBRARIES = /usr/lib64/libglib-2.0.so;/usr/lib64/libgthread-2.0.so;/usr/lib64/libgmodule-2.0.so
    -- Found Tor path = /homes/user/src/shadow-plugin-tor/build/tor
    -- Found Tor version = 0.2.7.6
    -- Added definition SCALLION_NEWIDKEYNAME
    -- Added definition SCALLION_DOREFILLCALLBACKS
    -- Added definition SCALLION_NEWCRYPTODEFS
    -- Added definition SCALLION_USEV2CPUWORKER
    -- Added definition SCALLION_USEV2CPUWORKERTIMING
    -- Added definition SCALLION_LOGVWITHSUFFIX
    -- Added definition SCALLION_NOV2DIR
    -- Added definition SCALLION_MEMPOOLOPT
    -- Added definition STARTUP_Q_PARAM
    CMake Error at src/tor/CMakeLists.txt:163 (add_shadow_plugin):
      Unknown CMake command add_shadow_plugin.

    -- Configuring incomplete, errors occurred!
    See also /homes/user/src/shadow-plugin-tor/build/main/CMakeFiles/CMakeOutput.log.
    See also /homes/user/src/shadow-plugin-tor/build/main/CMakeFiles/CMakeError.log.
    2016-03-02 16:36:50,617 INFO cmake returned 1
    [2016-03-02 16:36:50.618511] Shadow Setup: ERROR! Non-zero return code from cmake.
    2016-03-02 16:36:50,619 INFO returning code '1'

**Comment by dmS0Zq** [comment]
I see that add_shadow_plugin is defined as a macro in LLVMTools.cmake in the shadow code. https://github.com/shadow/shadow/blob/master/cmake/LLVMTools.cmake#L168 

I'm not sure how that's supposed to make it over to shadow-plugin-tor. Then again, I've never used cmake before.

**Comment by robgjansen** [comment]
You need to install Shadow first. Have you done that?

https://github.com/shadow/shadow/wiki/1-Installation-and-Setup

**Comment by dmS0Zq** [comment]
Yes.

**Comment by dmS0Zq** [comment]
Well now it compiles and installs fine, but now I have issues actually running it. Time to start from scratch a third time. Thanks!
