### ISSUE TITLE
LLVMHoistGlobalsPATH path does not exist

### ISSUE THREAD

**Issue by chelseakomlo** [shadow/shadow-plugin-tor#33]
I receive the following error for  ```./setup build```. 

```
CMake Error at CMakeLists.txt:89 (message):
  LLVMHoistGlobalsPATH path does not exist:
  '/root/.shadow/lib/LLVMHoistGlobals.so'
```

I do have llvm, but it is version > 3.2. However, I'm not sure this is the source of the above issue.

Thanks!

**Comment by robgjansen** [comment]
You need to [install Shadow](https://github.com/shadow/shadow/wiki/1-Installation-and-Setup) first. Have you done that?

(Also, you may run into a problem if you install some of these components as root and some as a non-root user. You should not need to use root privileges at all - not during installation and not to run Shadow.)

**Comment by chelseakomlo** [comment]
Thank you- that was exactly the issue! Apologies, I see that step is noted on the wiki. 

I haven't run into issues with the path- I'm building this in a Docker container, but mapped to a local Tor source directory. I see on the wiki that there is a Docker image available for Shadow- is the source for this published anywhere? It would be really useful to compare.

**Comment by robgjansen** [comment]
The docker image was contributed by some colleagues from Georgetown University, and I don't have the source. Sorry! The instructions are on the wiki to recreate the docker image, though, in case that helps.

**Comment by xwu64** [comment]
I follow instruction `./setup build --clean --debug --test`  to install shadow. However, in the directory `.shadow/lib`, there is not LLVMHoistGlobals.so file.

**Comment by xwu64** [comment]
I'm sure shadow and bitcoin plugin is the latest version. Which one should be updated?
