### ISSUE TITLE
Generating shadow.config.xml is complete - but file is not found

### ISSUE THREAD

**Issue by saurav-sahu** [shadow/shadow-plugin-tor#38]
Trying to generate config file with the command:

`bash -v gen.sh 1 20 200 20 0.90 0.10 10 10 10`

`python ~/shadow-plugin-tor/tools/generate.py  --nauths $1 --nrelays $2 --nclients $3 --nservers $4 --fweb $5 --fbulk $6 --nperf50k $7 --nperf1m $8 --nperf5m $9 ../alexa-top-1000-ips.csv  /home/tor/shadow-plugin-tor/resource/gen/consensuses-2017-08/22/2017-08-22-03-00-00-consensus ../server-descriptors-2017-08/ ../extra-infos-2017-08/ ../clients.csv`
### Output
`[2017-08-25 10:48:48.056605] Warning: Cant find code for IP '104.244.42.129' Num '1760832129', defaulting to 'US'`
`[2017-08-25 10:48:48.947460] Warning: Cant find code for IP '185.88.181.10' Num '3109598474', defaulting to 'US'`
`[2017-08-25 10:48:51.228167] Warning: Cant find code for IP '103.49.221.211' Num '1731321299', defaulting to 'US'`
`[2017-08-25 10:48:51.271360] Warning: Cant find code for IP '103.68.220.61' Num '1732566077', defaulting to 'US'`
`[2017-08-25 10:48:51.676946] Warning: Cant find code for IP '185.89.12.132' Num '3109620868', defaulting to 'US'`
`[2017-08-25 10:48:52.147862] Warning: Cant find code for IP '185.147.178.11' Num '3113464331', defaulting to 'US'`
`[2017-08-25 10:48:55.868339] Warning: Cant find code for IP '104.197.41.230' Num '1757751782', defaulting to 'US'`
`[2017-08-25 10:48:55.907706] Warning: Cant find code for IP '185.179.62.2' Num '3115531778', defaulting to 'US'`
`[2017-08-25 10:48:56.174763] Warning: Cant find code for IP '185.143.233.2' Num '3113216258', defaulting to 'US'`
`[2017-08-25 10:48:57.278118] Warning: Cant find code for IP '104.192.140.65' Num '1757449281', defaulting to 'US'`
`[2017-08-25 10:48:57.514216] Warning: Cant find code for IP '185.134.202.6' Num '3112618502', defaulting to 'US'`
`[2017-08-25 10:48:57.953950] Warning: Cant find code for IP '103.58.114.101' Num '1731883621', defaulting to 'US'`
`[2017-08-25 10:48:58.040003] Warning: Cant find code for IP '220.158.132.187' Num '3701376187', defaulting to 'US'`
`[2017-08-25 10:48:58.732528] Warning: Cant find code for IP '185.195.230.7' Num '3116623367', defaulting to 'US'`
`[2017-08-25 10:48:59.741029] Warning: Cant find code for IP '185.104.133.10' Num '3110634762', defaulting to 'US'`
`[2017-08-25 10:49:00.536059] Warning: Cant find code for IP '185.167.74.20' Num '3114748436', defaulting to 'US'`
`[2017-08-25 10:49:01.161418] Warning: Cant find code for IP '45.116.91.1' Num '762600193', defaulting to 'US'`
`[2017-08-25 10:49:01.214249] Warning: Cant find code for IP '45.60.40.25' Num '758917145', defaulting to 'US'`
`[2017-08-25 10:49:02.826518] Warning: Cant find code for IP '45.34.10.165' Num '757205669', defaulting to 'US'`
`[2017-08-25 10:49:03.833991] Warning: Cant find code for IP '104.192.143.1' Num '1757449985', defaulting to 'US'`
`[2017-08-25 10:49:04.274460] Warning: Cant find code for IP '185.94.140.30' Num '3109981214', defaulting to 'US'`
`[2017-08-25 10:49:04.741456] Warning: Cant find code for IP '104.254.87.63' Num '1761498943', defaulting to 'US'`
`[2017-08-25 10:49:04.983743] Warning: Cant find code for IP '185.94.84.100' Num '3109966948', defaulting to 'US'`
`[2017-08-25 10:49:05.959822] Warning: Cant find code for IP '185.129.44.25' Num '3112250393', defaulting to 'US'`
`[2017-08-25 10:49:07.128862] Warning: Cant find code for IP '185.113.25.60' Num '3111196988', defaulting to 'US'`
`[2017-08-25 10:49:08.284027] Warning: Cant find code for IP '185.66.120.38' Num '3108141094', defaulting to 'US'`
`[2017-08-25 10:49:08.536265] Warning: Cant find code for IP '45.113.70.192' Num '762398400', defaulting to 'US'`
`[2017-08-25 10:49:08.792923] Warning: Cant find code for IP '103.194.153.149' Num '1740806549', defaulting to 'US'`
`[2017-08-25 10:49:09.023526] Warning: Cant find code for IP '192.124.249.153' Num '3229415833', defaulting to 'US'`
`[2017-08-25 10:58:00.829663] finished generating /home/tor/shadow-plugin-tor/resource/gen/mytor/shadow.data.template/hosts/4uthority1/shadow.config.xml`

### Expected Behaviour
shadow.config.xml generated in the 4uthority directory

### Actual Behaviour
`ls shadow.data.template/hosts/4uthority1/` shows an empty directory listing

**Comment by robgjansen** [comment]
I think that the `shadow.config.xml` file should be written in the directory from which you called `generate.py`, it does not get written to the `shadow.data.template/hosts/4uthority1/` directory. Although I see that the last message in the output indicates otherwise.

I am assuming that you are running the `generate.py` script from the `/home/tor/shadow-plugin-tor/resource/gen/mytor/` directory. Is that right? Or are you running it from the `4uthority1/` directory?

**Comment by saurav-sahu** [comment]
I am running the script from the `mytor` directory.

**Comment by saurav-sahu** [comment]
There was an installation of the Tor Browser in my `/home/tor/Downloads` directory which used to start up whenever the generation of `shadow.config.xml` reached the final stages. After deleting that installation, the files were properly generated.
