### ISSUE TITLE
Fatal error: glibc detected an invalid stdio handle

### ISSUE THREAD

**Issue by isislovecruft** [shadow/shadow-plugin-tor#39]
Running a shadow-minimal network, only 10/40 downloads completed, and `Fatal error: glibc detected an invalid stdio handle` was output several times towards the end. Going back to `shadow.git` and doing `./setup build --test` and then running the tests, the same error was output during a file-shadow test, which failed. Attached are the logs of the test. Please let me know if there's other data I can collect about the issue.

[LastTest.log](https://github.com/shadow/shadow-plugin-tor/files/1383735/LastTest.log)
[file.shadow.data.zip](https://github.com/shadow/shadow-plugin-tor/files/1383744/file.shadow.data.zip)

(Sorry for the .zip, Github doesn't allow uploading .tar.*)

**Comment by robgjansen** [comment]
Thanks @isislovecruft!

(The failed test above was run on Fedora 25.)

**Comment by jtracey** [comment]
This was (hopefully!) fixed in https://github.com/shadow/shadow/commit/515c1a12f8cbeb82b27383691cade82f1aa4b222.

**Comment by robgjansen** [comment]
I'm assuming this is working now per the previous comment. Please re-open if there is still an error.
