### ISSUE TITLE
Error about "Could not open ro target file"

### ISSUE THREAD

**Issue by non1996** [shadow/shadow-plugin-tor#42]
I have passed the Shadow basic functional tests. But when I ran `shadowtor-toy-config`, it appeared that:

```
** Starting Shadow v1.12.0-34-ge7bcce8 2017-11-30 (built 2017-12-03) with GLib v2.48.2 and IGraph v0.7.1
/home/ubuntu/shadow/src/external/elf-loader/vdl-map.c:802:vdl_file_map_single: Could not open ro target file: /home/ubuntu/libshadow-plugin-torctl.so
/home/ubuntu/shadow/src/external/elf-loader/vdl-map.c:976, vdl_file_map_single_maybe, Attempted mapping failed. Try adjusting your system's max_map_count.
Segmentation fault (core dumped) 
```

I don't know what's wrong. The system I use is Ubuntu server 16.04.1 LTS 64-bit, and Tor version is 0.3.1.7.

Finally it works after I increase the system limits, but the return value is -1 like this:

```
** Starting Shadow v1.12.0-34-ge7bcce8 2017-11-30 (built 2017-12-03) with GLib v2.48.2 and IGraph v0.7.1
** Stopping Shadow, returning code -1 (error)
```

**Comment by robgjansen** [comment]
The error `Attempted mapping failed. Try adjusting your system's max_map_count.` indicates that you have used up all of the maps allowed to your process, so you will want to increase it. See the wiki page here:
https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-maps

**Comment by non1996** [comment]
The error did not appear after I adjusted the system limits include `max_map_count`, but the return value of shadow is -1. This return value appeared also when I run `shadowtor-minimal` test. It's there something else should I configure?

I set `max_map_count` to `1073741824`.

Return valure is:
```
** Starting Shadow v1.12.0-34-ge7bcce8 2017-11-30 (built 2017-12-03) with GLib v2.48.2 and IGraph v0.7.1
** Stopping Shadow, returning code -1 (error)
```

**Comment by robgjansen** [comment]
This probably is due to an unrelated issue shadow/shadow#369 that I fixed yesterday. Try pulling down the latest version of Shadow from Github (you are missing just one commit as of now). That should get you up to `Shadow v1.12.0-35`, and hopefully fix things for you!

**Comment by non1996** [comment]
It works, thanks for your help! :D
