### ISSUE TITLE
Can't build: error when linking libshadow-plugin-tor.so

### ISSUE THREAD

**Issue by valentecaio** [shadow/shadow-plugin-tor#44]
I'm trying to build shadow-plugin-tor using the newest version of Tor (commit ID 48a51c5f8b80a359da31bc5aaac8ecd25890fe0d) but it seems that a Tor global variable called tor_git_version is being redeclared.

When trying make, I have the following output:

![contribution1](https://user-images.githubusercontent.com/14484616/35195816-3a53f160-fec9-11e7-9b37-ceb1f88db3f7.png)

**Comment by robgjansen** [comment]
Thanks for reporting this bug! Yeah, it seems like we should not redeclare `tor_git_revision` in newer versions of Tor, as you recommended.

The short term fix is to just remove it from `src/tor/shadowtor-main.c` as you did. Thanks for testing that it works!

If we want to support previous versions of Tor (which I think we do), we need to be able to determine if `tor_git_revision` already exists, and define it **only** if it doesn't. Hmm... not sure the best way to do that.

How about we exclude `tor/src/or/git_revision.c` from the list of files that we build into `shadow-plugin-tor`, keep the definition in `src/tor/shadowtor-main.c`, and then at some point in the future we swap over and no longer support versions of Tor that don't contain `tor/src/or/git_revision.c`?

**Comment by robgjansen** [comment]
Note that the fix will only get applied correctly starting at `0.3.3.1-alpha` or later. Between now and then, you'll have to manually remove the `tor_git_revision` to build correctly. (We don't track Tor versions at the commit level, only at the tag level.)

**Comment by valentecaio** [comment]
Thanks for your answer and your help @jtracey !

I was working on it right now, also trying to use a macro, then I decided to reclone the repo and it came with your solution haha
