### ISSUE TITLE
generate.py tor.browser.torrc and MaxCircuitDirtiness

### ISSUE THREAD

**Issue by frochet** [shadow/shadow-plugin-tor#48]
Hello,

I was surprised to find a 30 sec dirtiness for labeled torbrowser torrc file, while the dirtiness is 600 sec in the real Tor network. I am trying to understand your choice and I am maybe missing something?

Best,

**Comment by robgjansen** [comment]
IIRC, Tor browser generally uses a new circuit every time the URL that appears in the URL bar changes. This behavior would not happen in Shadow, however, because we don't run the same logic that TBB uses (TBB sets the socks username to the URL, and TBB makes sure that Tor isolates streams by the socks username).

So, we use `MaxCircuitDirtiness` to try to get closer to a new circuit for every site in simulation.

Does this make sense?

**Comment by frochet** [comment]
Hey,

Thanks for your fast answer! It indeed clears things up. So, I think you could mimic pretty good TBB by isolating streams with the destination address, e.g.:

SocksPort 9000 IsolateDestAddr

And you keep MaxCircuitDirtiness to default. Normally, each time tgen picks a new server, we should get a new circuit. And, if tgen picks again a server we used before, and the 10 minutes did not elapse, you would reuse a previous circuit. 

What do you think?

**Comment by robgjansen** [comment]
I don't think that will work. Consider a site `www.example.com` that has 100 embedded images that all come from different servers. In TBB, all 100 images will be transferred over the same circuit that was used to fetch `www.example.com`. However, if we use `SocksPort 9000 IsolateDestAddr`, these images will cause 100 circuits to be built.

My circuit dirtiness approach is invalid only in the case that a user goes to a site, and 30 < t < 600 seconds later tries to access the same site again. In TBB, both visits would use the same circuit; in Shadow, that will use 2 circuits. But in Shadow, we care less about specific users, and more about general usage. So, if you think of these 2 visits as coming from separate users, then I think it's OK.

**Comment by frochet** [comment]
>I don't think that will work. Consider a site www.example.com that has 100 embedded images that all come from different servers. In TBB, all 100 images will be transferred over the same circuit that was used to fetch www.example.com. However, if we use SocksPort 9000 IsolateDestAddr, these images will cause 100 circuits to be built.

Didn't know that Shadow pushed things that far. It is possible to do web simulations with cross-origin get of content then?

>My circuit dirtiness approach is invalid only in the case that a user goes to a site, and 30 < t < 600 seconds later tries to access the same site again. In TBB, both visits would use the same circuit; in Shadow, that will use 2 circuits. But in Shadow, we care less about specific users, and more about general usage. So, if you think of these 2 visits as coming from separate users, then I think it's OK.

Yes it makes sense, thank you!

**Comment by robgjansen** [comment]
> It is possible to do web simulations with cross-origin get of content then?

Sure! You can make arbitrary requests using our traffic generator: anything that can be modeled by a dependency graph:
https://github.com/shadow/shadow/wiki/3.3-TGen-Config

I'm going to close the issue as answered, please re-open if needed.
