### ISSUE TITLE
vdl_file_map_single: Could not open ro target file... Segmentation fault

### ISSUE THREAD

**Issue by juga0** [shadow/shadow-plugin-tor#58]
I can successfully run shadow-plugin-tor with ``resource/shadow-minimal``, but i can't with ``resource/vanilla``:

```
/mypath/shadow-plugin-tor/resource/vanilla$ shadow -w 3 shadow.config.xml > shadow.log
** Starting Shadow v1.13.0-11-g1190a345 2018-08-03 (built 2018-10-10) with GLib v2.50.3 and IGraph v0.7.1
/mypath/shadow/src/external/elf-loader/vdl-map.c:805:vdl_file_map_single: Could not open ro target file: /mypath/.shadow/lib/libshadow-plugin-torctl.so
/mypath/shadow/src/external/elf-loader/vdl-map.c:979, vdl_file_map_single_maybe, Attempted mapping failed. Try adjusting your system's max_map_count.
Segmentation fault
```
This seems to be the same as #42, except that i've compiled shadow from the last commit in master. I've not tried with the same commit that solved the problem in #42.

I've increased the maps as explained in https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-maps, but still get the same error.

Any ideas on how to fix this?. Thanks

**Comment by jtracey** [comment]
That error means the OS is returning an error trying to open that file. Make sure that `/mypath/.shadow/lib/libshadow-plugin-torctl.so` is readable, otherwise I would guess that either the max maps or [file descriptors](https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-open-files) is still too low.

**Comment by robgjansen** [comment]
@juga0 were you able to adjust your system limits correctly?

**Comment by juga0** [comment]
yeah!, i increased the number of maps, file descriptors and user file limit to 1073741824.
It probably can work with lower numbers, but i think after changing ``/etc/security/limits.conf`` i had to reboot or logout/login the user (maybe something to clarify in the doc?). It finally worked when i did.
I wonder if there's a way to figure out those limits without try/error.
Thanks a lot!

**Comment by jtracey** [comment]
@juga0 I agree a deterministic number to give the user would be nice, but unfortunately, the number of open file descriptors or maps depends on the behavior of the simulated processes, and if you try to predict whether the simulation will crash from the current limit or not, you quickly run into the whole ["halting problem"](https://en.wikipedia.org/wiki/Halting_problem) thing. :P

**Comment by robgjansen** [comment]
According to the docs, first you need to update the allowed **system** limits

```bash
sudo sysctl -w vm.max_map_count=1073741824
sudo sysctl -w fs.nr_open=10485760
sudo sysctl -w fs.file-max=10485760
sudo sysctl -p

sudo echo "vm.max_map_count = 1073741824" >> /etc/sysctl.conf
sudo echo "fs.nr_open = 10485760" >> /etc/sysctl.conf
sudo echo "fs.file-max = 10485760" >> /etc/sysctl.conf
```

After the **system** limits are update, you can then update the limits for the **user** with which you are running shadow (named `rjansen` here) by adding this to `/etc/security/limits.conf`

```
rjansen soft nofile 10485760
rjansen hard nofile 10485760
```

Then you want to **either reboot, or log out and then log back in**, and verify that your settings from above have been applied correctly, both for the **system** limits and for the **user** limits:

```
sysctl vm.max_map_count
sysctl fs.nr_open
sysctl fs.file-max
ulimit -n
```

Make sure the settings are applied correctly before running shadow.

**Comment by pmicos** [comment]
No, I'm just running Shadow in an Ubuntu 18.04 virtual machine.

**Comment by robgjansen** [comment]
Hmm, I wonder if `10485760` is too large for your VM and so the limit is not being applied correctly? Maybe try setting a limit that is smaller than `10485760`, to see if that gets it to stick?

**Comment by sporksmith** [comment]
I've run into this on ubuntu 18.04 as well. I've been working around it by running as root, which obviously is not ideal :/
