### ISSUE TITLE
i tried to run KIST algorithm i have also tried increasing ulimt values but couldnt get through 

### ISSUE THREAD

**Issue by keethu0519** [shadow/shadow-plugin-tor#59]
```
sai@sai-VirtualBox:~$ cd shadow
sai@sai-VirtualBox:~/shadow$ cd shadow-plugin-tor
sai@sai-VirtualBox:~/shadow/shadow-plugin-tor$ cd resource
sai@sai-VirtualBox:~/shadow/shadow-plugin-tor/resource$ tar xaf shadowtor-minimal-config.tar.xz
sai@sai-VirtualBox:~/shadow/shadow-plugin-tor/resource$ cp -R shadowtor-minimal-config KIST
sai@sai-VirtualBox:~/shadow/shadow-plugin-tor/resource$ cd KIST
sai@sai-VirtualBox:~/shadow/shadow-plugin-tor/resource/KIST$ shadow -w 3 shadow.config.xml > shadow9.log
** Starting Shadow v1.13.0-11-g1190a345 2018-08-03 (built 2018-10-10) with GLib v2.56.2 and IGraph v0.7.1
/home/sai/shadow/src/external/elf-loader/vdl-map.c:805:vdl_file_map_single: Could not open ro target file: /home/sai/.shadow/lib/libshadow-plugin-torctl.so
/home/sai/shadow/src/external/elf-loader/vdl-map.c:979, vdl_file_map_single_maybe, Attempted mapping failed. Try adjusting your system's max_map_count.
Segmentation fault (core dumped)
```

**Comment by robgjansen** [comment]
There error is: `Could not open ro target file: /home/sai/.shadow/lib/libshadow-plugin-torctl.so`

Make sure you have successfully built and installed shadow-plugin-tor, and make sure that the file exists in the correct location: `/home/sai/.shadow/lib/libshadow-plugin-torctl.so`.

If so, then the suggested fix is `Try adjusting your system's max_map_count.`, which is explained further [on the wiki](https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-maps). See also #58 where someone else had the same issue. (You may need to log out/in or restart after updating the map_max_count to make sure you OS applies the change.)

Please let us know if you get things working.

**Comment by robgjansen** [comment]
Glad you got it working!

There is no database of Shadow-Tor simulation network configurations. I would like to create a page on the wiki that people can use to link to their own configurations, but so far that doesn't exist.

The most recent configurations that I have used are posted here:
https://tmodel-ccs2018.github.io/
(See Shadow host configuration at the bottom of the page.)

These are somewhat resource intensive, so it might be better to generate your own.
https://github.com/shadow/shadow-plugin-tor/wiki#generating-a-new-tor-network

**Comment by keethu0519** [comment]
Thanks for the information.
I tried to create the simulation config file using 
python ~/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 20 --nclients 200 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 100 --nperf1m 50 --nperf5m 50 /home/sai/shadow-plugin-tor/tools/parsealexa.py /home/sai/2018-10-20-18-00-00-consensus  /home/sai/server-descriptors-2017-01 /home/sai/extra-infos-2017-01 /home/sai/clients.csv
but the data is not generated and  the terminal is still There is no errors. How  much time is estimated for this process?

**Comment by robgjansen** [comment]
There is a lot of data to process so it can take some time (maybe a few hours). Please be patient.

**Comment by keethu0519** [comment]
python ~/shadow/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 20 --nclients 100 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 50 --nperf1m 25 --nperf5m 25 /home/sai/shadow-plugin-tor/tools/parsealexa.py /home/sai/2018-10-20-18-00-00-consensus /home/sai/2018-10-21-17-05-00-server-descriptors /home/sai/2018-10-21-17-05-00-extra-infos /home/sai/clients.csv
Traceback (most recent call last):
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 1132, in <module>
    main()
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 214, in main
    generate(args)
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 264, in generate
    servers = getServers(geoentries, args.alexa)
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 766, in getServers
    ip = parts[2]
IndexError: list index out of range

how do i fix this?
