### ISSUE TITLE
please ensure 'tor' and 'tor-gencert' are in your 'PATH'

### ISSUE THREAD

**Issue by keethu0519** [shadow/shadow-plugin-tor#60]
i am trying to create configuration data for the simulation.
i have checked that the path specified contains 'tor' and 'tor-gencert' files but still i am getting the error.
what could be possibly wrong?

```
sudo python ~/shadow/shadow-plugin-tor/tools/generate.py -p /home/sai/shadow-plugin-tor/build/tor/src/tools --nauths 1 --nrelays 20 --nclients 200 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 20 --nperf1m 10 --nperf5m 10 /home/sai/shadow-plugin-tor/tools/parsealexa.py /home/sai/2018-10-20-18-00-00-consensus /home/sai/2018-10-21-17-05-00-server-descriptors /home/sai/2018-10-21-17-05-00-extra-infos /home/sai/clients.csv
[2018-10-25 18:29:07.487831] please ensure 'tor' and 'tor-gencert' are in your 'PATH'
```

**Comment by robgjansen** [comment]
You are running as `sudo`, which means you are running as the root user and that will use the root user's PATH variable. You don't need to, and you should not be running as root. Just execute the command again as the regular user.

**Comment by keethu0519** [comment]
i tried to execute the command as regular user but i am still getting the same error please ensure 'tor' and 'tor-gencert' are in your 'PATH'

when i looked up i did not file the binary file for tor but there was a binary execution for gencert.
how do i solve this? i reinstalled shadow but it doesn't solve my issue
ls -l /home/sai/shadow/shadow-plugin-tor/build/tor/src/tools/ | grep gencert
-rwxr-xr-x 1 sai sai 3442120 Oct 29 14:55 tor-gencert
-rw-r--r-- 1 sai sai   16709 Oct 19  2017 tor-gencert.c
-rw-r--r-- 1 sai sai   23896 Oct 29 14:55 tor-gencert.o
sai@sai-VirtualBox:~/mytor1$ ls -l /home/sai/shadow/shadow-plugin-tor/build/tor/src/or/ | grep tor
-rw-r--r-- 1 sai sai  216797 Dec 12  2017 directory.c
-rw-r--r-- 1 sai sai   13730 Nov 17  2017 directory.h
-rw-r--r-- 1 sai sai  176952 Oct 29 14:55 directory.o
-rw-r--r-- 1 sai sai   88081 Nov  6  2017 hs_descriptor.c
-rw-r--r-- 1 sai sai   11108 Nov  2  2017 hs_descriptor.h
-rw-r--r-- 1 sai sai   85808 Oct 29 14:55 hs_descriptor.o
-rw-r--r-- 1 sai sai   25280 Oct 19  2017 hs_ntor.c
-rw-r--r-- 1 sai sai    2933 Oct 19  2017 hs_ntor.h
-rw-r--r-- 1 sai sai   15744 Oct 29 14:55 hs_ntor.o
-rw-r--r-- 1 sai sai 4705410 Oct 29 14:55 libtor.a
-rw-r--r-- 1 sai sai 4816150 Oct 29 14:55 libtor-testing.a
-rw-r--r-- 1 sai sai   12566 Oct 19  2017 onion_ntor.c
-rw-r--r-- 1 sai sai    2213 Oct 19  2017 onion_ntor.h
-rw-r--r-- 1 sai sai    9616 Oct 29 14:55 onion_ntor.o
-rw-r--r-- 1 sai sai   29664 Oct 29 14:55 src_or_libtor_testing_a-addressmap.o
-rw-r--r-- 1 sai sai   27864 Oct 29 14:55 src_or_libtor_testing_a-bridges.o
-rw-r--r-- 1 sai sai  137544 Oct 29 14:55 src_or_libtor_testing_a-channel.o
-rw-r--r-- 1 sai sai   16312 Oct 29 14:55 src_or_libtor_testing_a-channelpadding.o
-rw-r--r-- 1 sai sai   89528 Oct 29 14:55 src_or_libtor_testing_a-channeltls.o
-rw-r--r-- 1 sai sai   40968 Oct 29 14:55 src_or_libtor_testing_a-circpathbias.o
-rw-r--r-- 1 sai sai   82312 Oct 29 14:55 src_or_libtor_testing_a-circuitbuild.o
-rw-r--r-- 1 sai sai   71464 Oct 29 14:55 src_or_libtor_testing_a-circuitlist.o
-rw-r--r-- 1 sai sai   18592 Oct 29 14:55 src_or_libtor_testing_a-circuitmux_ewma.o
-rw-r--r-- 1 sai sai   52328 Oct 29 14:55 src_or_libtor_testing_a-circuitmux.o
-rw-r--r-- 1 sai sai   41536 Oct 29 14:55 src_or_libtor_testing_a-circuitstats.o
-rw-r--r-- 1 sai sai   75088 Oct 29 14:55 src_or_libtor_testing_a-circuituse.o
-rw-r--r-- 1 sai sai   25192 Oct 29 14:55 src_or_libtor_testing_a-command.o
-rw-r--r-- 1 sai sai  300696 Oct 29 14:55 src_or_libtor_testing_a-config.o
-rw-r--r-- 1 sai sai   37976 Oct 29 14:55 src_or_libtor_testing_a-confparse.o
-rw-r--r-- 1 sai sai  114312 Oct 29 14:55 src_or_libtor_testing_a-connection_edge.o
-rw-r--r-- 1 sai sai  160088 Oct 29 14:55 src_or_libtor_testing_a-connection.o
-rw-r--r-- 1 sai sai   81648 Oct 29 14:55 src_or_libtor_testing_a-connection_or.o
-rw-r--r-- 1 sai sai   15704 Oct 29 14:55 src_or_libtor_testing_a-conscache.o
-rw-r--r-- 1 sai sai   55608 Oct 29 14:55 src_or_libtor_testing_a-consdiffmgr.o
-rw-r--r-- 1 sai sai   32592 Oct 29 14:55 src_or_libtor_testing_a-consdiff.o
-rw-r--r-- 1 sai sai  230776 Oct 29 14:55 src_or_libtor_testing_a-control.o
-rw-r--r-- 1 sai sai   17672 Oct 29 14:55 src_or_libtor_testing_a-cpuworker.o
-rw-r--r-- 1 sai sai   14688 Oct 29 14:55 src_or_libtor_testing_a-dircollate.o
-rw-r--r-- 1 sai sai  179392 Oct 29 14:55 src_or_libtor_testing_a-directory.o
-rw-r--r-- 1 sai sai  105512 Oct 29 14:55 src_or_libtor_testing_a-dirserv.o
-rw-r--r-- 1 sai sai  119344 Oct 29 14:55 src_or_libtor_testing_a-dirvote.o
-rw-r--r-- 1 sai sai   68472 Oct 29 14:55 src_or_libtor_testing_a-dns.o
-rw-r--r-- 1 sai sai   12648 Oct 29 14:55 src_or_libtor_testing_a-dnsserv.o
-rw-r--r-- 1 sai sai  102712 Oct 29 14:55 src_or_libtor_testing_a-entrynodes.o
-rw-r--r-- 1 sai sai   17736 Oct 29 14:55 src_or_libtor_testing_a-ext_orport.o
-rw-r--r-- 1 sai sai   15496 Oct 29 14:55 src_or_libtor_testing_a-fp_pair.o
-rw-r--r-- 1 sai sai   57664 Oct 29 14:55 src_or_libtor_testing_a-geoip.o
-rw-r--r-- 1 sai sai   34640 Oct 29 14:55 src_or_libtor_testing_a-hibernate.o
-rw-r--r-- 1 sai sai   27448 Oct 29 14:55 src_or_libtor_testing_a-hs_cache.o
-rw-r--r-- 1 sai sai   37976 Oct 29 14:55 src_or_libtor_testing_a-hs_cell.o
-rw-r--r-- 1 sai sai   17944 Oct 29 14:55 src_or_libtor_testing_a-hs_circuitmap.o
-rw-r--r-- 1 sai sai   42432 Oct 29 14:55 src_or_libtor_testing_a-hs_circuit.o
-rw-r--r-- 1 sai sai   52648 Oct 29 14:55 src_or_libtor_testing_a-hs_client.o
-rw-r--r-- 1 sai sai   51504 Oct 29 14:55 src_or_libtor_testing_a-hs_common.o
-rw-r--r-- 1 sai sai   14664 Oct 29 14:55 src_or_libtor_testing_a-hs_config.o
-rw-r--r-- 1 sai sai   86776 Oct 29 14:55 src_or_libtor_testing_a-hs_descriptor.o
-rw-r--r-- 1 sai sai    4616 Oct 29 14:55 src_or_libtor_testing_a-hs_ident.o
-rw-r--r-- 1 sai sai   22032 Oct 29 14:55 src_or_libtor_testing_a-hs_intropoint.o
-rw-r--r-- 1 sai sai   15744 Oct 29 14:55 src_or_libtor_testing_a-hs_ntor.o
-rw-r--r-- 1 sai sai  104880 Oct 29 14:55 src_or_libtor_testing_a-hs_service.o
-rw-r--r-- 1 sai sai   19368 Oct 29 14:55 src_or_libtor_testing_a-keypin.o
-rw-r--r-- 1 sai sai  143992 Oct 29 14:55 src_or_libtor_testing_a-main.o
-rw-r--r-- 1 sai sai   36136 Oct 29 14:55 src_or_libtor_testing_a-microdesc.o
-rw-r--r-- 1 sai sai   72712 Oct 29 14:55 src_or_libtor_testing_a-networkstatus.o
-rw-r--r-- 1 sai sai   74464 Oct 29 14:55 src_or_libtor_testing_a-nodelist.o
-rw-r--r-- 1 sai sai    4312 Oct 29 14:55 src_or_libtor_testing_a-onion_fast.o
-rw-r--r-- 1 sai sai    9616 Oct 29 14:55 src_or_libtor_testing_a-onion_ntor.o
-rw-r--r-- 1 sai sai   31040 Oct 29 14:55 src_or_libtor_testing_a-onion.o
-rw-r--r-- 1 sai sai    7344 Oct 29 14:55 src_or_libtor_testing_a-onion_tap.o
-rw-r--r-- 1 sai sai   19456 Oct 29 14:55 src_or_libtor_testing_a-parsecommon.o
-rw-r--r-- 1 sai sai    5216 Oct 29 14:55 src_or_libtor_testing_a-periodic.o
-rw-r--r-- 1 sai sai   76568 Oct 29 14:55 src_or_libtor_testing_a-policies.o
-rw-r--r-- 1 sai sai    2912 Oct 29 14:55 src_or_libtor_testing_a-proto_cell.o
-rw-r--r-- 1 sai sai    1808 Oct 29 14:55 src_or_libtor_testing_a-proto_control0.o
-rw-r--r-- 1 sai sai    2240 Oct 29 14:55 src_or_libtor_testing_a-proto_ext_or.o
-rw-r--r-- 1 sai sai    6848 Oct 29 14:55 src_or_libtor_testing_a-proto_http.o
-rw-r--r-- 1 sai sai   21536 Oct 29 14:55 src_or_libtor_testing_a-proto_socks.o
-rw-r--r-- 1 sai sai   19680 Oct 29 14:55 src_or_libtor_testing_a-protover.o
-rw-r--r-- 1 sai sai   21072 Oct 29 14:55 src_or_libtor_testing_a-reasons.o
-rw-r--r-- 1 sai sai   88936 Oct 29 14:55 src_or_libtor_testing_a-relay.o
-rw-r--r-- 1 sai sai   31664 Oct 29 14:55 src_or_libtor_testing_a-rendcache.o
-rw-r--r-- 1 sai sai   40928 Oct 29 14:55 src_or_libtor_testing_a-rendclient.o
-rw-r--r-- 1 sai sai   31288 Oct 29 14:55 src_or_libtor_testing_a-rendcommon.o
-rw-r--r-- 1 sai sai   12584 Oct 29 14:55 src_or_libtor_testing_a-rendmid.o
-rw-r--r-- 1 sai sai  116152 Oct 29 14:55 src_or_libtor_testing_a-rendservice.o
-rw-r--r-- 1 sai sai   91088 Oct 29 14:55 src_or_libtor_testing_a-rephist.o
-rw-r--r-- 1 sai sai    5704 Oct 29 14:55 src_or_libtor_testing_a-replaycache.o
-rw-r--r-- 1 sai sai   42216 Oct 29 14:55 src_or_libtor_testing_a-routerkeys.o
-rw-r--r-- 1 sai sai  157392 Oct 29 14:55 src_or_libtor_testing_a-routerlist.o
-rw-r--r-- 1 sai sai  110992 Oct 29 14:55 src_or_libtor_testing_a-router.o
-rw-r--r-- 1 sai sai  193464 Oct 29 14:55 src_or_libtor_testing_a-routerparse.o
-rw-r--r-- 1 sai sai   16016 Oct 29 14:55 src_or_libtor_testing_a-routerset.o
-rw-r--r-- 1 sai sai   29952 Oct 29 14:55 src_or_libtor_testing_a-scheduler_kist.o
-rw-r--r-- 1 sai sai   21800 Oct 29 14:55 src_or_libtor_testing_a-scheduler.o
-rw-r--r-- 1 sai sai    6784 Oct 29 14:55 src_or_libtor_testing_a-scheduler_vanilla.o
-rw-r--r-- 1 sai sai   40424 Oct 29 14:55 src_or_libtor_testing_a-shared_random.o
-rw-r--r-- 1 sai sai   40104 Oct 29 14:55 src_or_libtor_testing_a-shared_random_state.o
-rw-r--r-- 1 sai sai   26032 Oct 29 14:55 src_or_libtor_testing_a-statefile.o
-rw-r--r-- 1 sai sai    7992 Oct 29 14:55 src_or_libtor_testing_a-status.o
-rw-r--r-- 1 sai sai   26272 Oct 29 14:55 src_or_libtor_testing_a-torcert.o
-rw-r--r-- 1 sai sai   49688 Oct 29 14:55 src_or_libtor_testing_a-transports.o
-rwxr-xr-x 1 sai sai 7231136 Oct 29 14:55 tor
-rwxr-xr-x 1 sai sai 7231136 Oct 29 14:55 tor.c
-rw-r--r-- 1 sai sai   23505 Oct 19  2017 torcert.c
-rw-r--r-- 1 sai sai    4214 Oct 19  2017 torcert.h
-rw-r--r-- 1 sai sai   25936 Oct 29 14:55 torcert.o
-rw-r--r-- 1 sai sai    1004 Oct 19  2017 tor_main.c
-rw-r--r-- 1 sai sai    1608 Oct 29 14:55 tor_main.o
sai@sai-VirtualBox:~/mytor1$ ls -l /home/sai/shadow/shadow-plugin-tor/build/tor/src/or/ | grep tor
-rw-r--r-- 1 sai sai  216797 Dec 12  2017 directory.c
-rw-r--r-- 1 sai sai   13730 Nov 17  2017 directory.h
-rw-r--r-- 1 sai sai  176952 Oct 29 14:55 directory.o
-rw-r--r-- 1 sai sai   88081 Nov  6  2017 hs_descriptor.c
-rw-r--r-- 1 sai sai   11108 Nov  2  2017 hs_descriptor.h
-rw-r--r-- 1 sai sai   85808 Oct 29 14:55 hs_descriptor.o
-rw-r--r-- 1 sai sai   25280 Oct 19  2017 hs_ntor.c
-rw-r--r-- 1 sai sai    2933 Oct 19  2017 hs_ntor.h
-rw-r--r-- 1 sai sai   15744 Oct 29 14:55 hs_ntor.o
-rw-r--r-- 1 sai sai 4705410 Oct 29 14:55 libtor.a
-rw-r--r-- 1 sai sai 4816150 Oct 29 14:55 libtor-testing.a
-rw-r--r-- 1 sai sai   12566 Oct 19  2017 onion_ntor.c
-rw-r--r-- 1 sai sai    2213 Oct 19  2017 onion_ntor.h
-rw-r--r-- 1 sai sai    9616 Oct 29 14:55 onion_ntor.o
-rw-r--r-- 1 sai sai   29664 Oct 29 14:55 src_or_libtor_testing_a-addressmap.o
-rw-r--r-- 1 sai sai   27864 Oct 29 14:55 src_or_libtor_testing_a-bridges.o
-rw-r--r-- 1 sai sai  137544 Oct 29 14:55 src_or_libtor_testing_a-channel.o
-rw-r--r-- 1 sai sai   16312 Oct 29 14:55 src_or_libtor_testing_a-channelpadding.o
-rw-r--r-- 1 sai sai   89528 Oct 29 14:55 src_or_libtor_testing_a-channeltls.o
-rw-r--r-- 1 sai sai   40968 Oct 29 14:55 src_or_libtor_testing_a-circpathbias.o
-rw-r--r-- 1 sai sai   82312 Oct 29 14:55 src_or_libtor_testing_a-circuitbuild.o
-rw-r--r-- 1 sai sai   71464 Oct 29 14:55 src_or_libtor_testing_a-circuitlist.o
-rw-r--r-- 1 sai sai   18592 Oct 29 14:55 src_or_libtor_testing_a-circuitmux_ewma.o
-rw-r--r-- 1 sai sai   52328 Oct 29 14:55 src_or_libtor_testing_a-circuitmux.o
-rw-r--r-- 1 sai sai   41536 Oct 29 14:55 src_or_libtor_testing_a-circuitstats.o
-rw-r--r-- 1 sai sai   75088 Oct 29 14:55 src_or_libtor_testing_a-circuituse.o
-rw-r--r-- 1 sai sai   25192 Oct 29 14:55 src_or_libtor_testing_a-command.o
-rw-r--r-- 1 sai sai  300696 Oct 29 14:55 src_or_libtor_testing_a-config.o
-rw-r--r-- 1 sai sai   37976 Oct 29 14:55 src_or_libtor_testing_a-confparse.o
-rw-r--r-- 1 sai sai  114312 Oct 29 14:55 src_or_libtor_testing_a-connection_edge.o
-rw-r--r-- 1 sai sai  160088 Oct 29 14:55 src_or_libtor_testing_a-connection.o
-rw-r--r-- 1 sai sai   81648 Oct 29 14:55 src_or_libtor_testing_a-connection_or.o
-rw-r--r-- 1 sai sai   15704 Oct 29 14:55 src_or_libtor_testing_a-conscache.o
-rw-r--r-- 1 sai sai   55608 Oct 29 14:55 src_or_libtor_testing_a-consdiffmgr.o
-rw-r--r-- 1 sai sai   32592 Oct 29 14:55 src_or_libtor_testing_a-consdiff.o
-rw-r--r-- 1 sai sai  230776 Oct 29 14:55 src_or_libtor_testing_a-control.o
-rw-r--r-- 1 sai sai   17672 Oct 29 14:55 src_or_libtor_testing_a-cpuworker.o
-rw-r--r-- 1 sai sai   14688 Oct 29 14:55 src_or_libtor_testing_a-dircollate.o
-rw-r--r-- 1 sai sai  179392 Oct 29 14:55 src_or_libtor_testing_a-directory.o
-rw-r--r-- 1 sai sai  105512 Oct 29 14:55 src_or_libtor_testing_a-dirserv.o
-rw-r--r-- 1 sai sai  119344 Oct 29 14:55 src_or_libtor_testing_a-dirvote.o
-rw-r--r-- 1 sai sai   68472 Oct 29 14:55 src_or_libtor_testing_a-dns.o
-rw-r--r-- 1 sai sai   12648 Oct 29 14:55 src_or_libtor_testing_a-dnsserv.o
-rw-r--r-- 1 sai sai  102712 Oct 29 14:55 src_or_libtor_testing_a-entrynodes.o
-rw-r--r-- 1 sai sai   17736 Oct 29 14:55 src_or_libtor_testing_a-ext_orport.o
-rw-r--r-- 1 sai sai   15496 Oct 29 14:55 src_or_libtor_testing_a-fp_pair.o
-rw-r--r-- 1 sai sai   57664 Oct 29 14:55 src_or_libtor_testing_a-geoip.o
-rw-r--r-- 1 sai sai   34640 Oct 29 14:55 src_or_libtor_testing_a-hibernate.o
-rw-r--r-- 1 sai sai   27448 Oct 29 14:55 src_or_libtor_testing_a-hs_cache.o
-rw-r--r-- 1 sai sai   37976 Oct 29 14:55 src_or_libtor_testing_a-hs_cell.o
-rw-r--r-- 1 sai sai   17944 Oct 29 14:55 src_or_libtor_testing_a-hs_circuitmap.o
-rw-r--r-- 1 sai sai   42432 Oct 29 14:55 src_or_libtor_testing_a-hs_circuit.o
-rw-r--r-- 1 sai sai   52648 Oct 29 14:55 src_or_libtor_testing_a-hs_client.o
-rw-r--r-- 1 sai sai   51504 Oct 29 14:55 src_or_libtor_testing_a-hs_common.o
-rw-r--r-- 1 sai sai   14664 Oct 29 14:55 src_or_libtor_testing_a-hs_config.o
-rw-r--r-- 1 sai sai   86776 Oct 29 14:55 src_or_libtor_testing_a-hs_descriptor.o
-rw-r--r-- 1 sai sai    4616 Oct 29 14:55 src_or_libtor_testing_a-hs_ident.o
-rw-r--r-- 1 sai sai   22032 Oct 29 14:55 src_or_libtor_testing_a-hs_intropoint.o
-rw-r--r-- 1 sai sai   15744 Oct 29 14:55 src_or_libtor_testing_a-hs_ntor.o
-rw-r--r-- 1 sai sai  104880 Oct 29 14:55 src_or_libtor_testing_a-hs_service.o
-rw-r--r-- 1 sai sai   19368 Oct 29 14:55 src_or_libtor_testing_a-keypin.o
-rw-r--r-- 1 sai sai  143992 Oct 29 14:55 src_or_libtor_testing_a-main.o
-rw-r--r-- 1 sai sai   36136 Oct 29 14:55 src_or_libtor_testing_a-microdesc.o
-rw-r--r-- 1 sai sai   72712 Oct 29 14:55 src_or_libtor_testing_a-networkstatus.o
-rw-r--r-- 1 sai sai   74464 Oct 29 14:55 src_or_libtor_testing_a-nodelist.o
-rw-r--r-- 1 sai sai    4312 Oct 29 14:55 src_or_libtor_testing_a-onion_fast.o
-rw-r--r-- 1 sai sai    9616 Oct 29 14:55 src_or_libtor_testing_a-onion_ntor.o
-rw-r--r-- 1 sai sai   31040 Oct 29 14:55 src_or_libtor_testing_a-onion.o
-rw-r--r-- 1 sai sai    7344 Oct 29 14:55 src_or_libtor_testing_a-onion_tap.o
-rw-r--r-- 1 sai sai   19456 Oct 29 14:55 src_or_libtor_testing_a-parsecommon.o
-rw-r--r-- 1 sai sai    5216 Oct 29 14:55 src_or_libtor_testing_a-periodic.o
-rw-r--r-- 1 sai sai   76568 Oct 29 14:55 src_or_libtor_testing_a-policies.o
-rw-r--r-- 1 sai sai    2912 Oct 29 14:55 src_or_libtor_testing_a-proto_cell.o
-rw-r--r-- 1 sai sai    1808 Oct 29 14:55 src_or_libtor_testing_a-proto_control0.o
-rw-r--r-- 1 sai sai    2240 Oct 29 14:55 src_or_libtor_testing_a-proto_ext_or.o
-rw-r--r-- 1 sai sai    6848 Oct 29 14:55 src_or_libtor_testing_a-proto_http.o
-rw-r--r-- 1 sai sai   21536 Oct 29 14:55 src_or_libtor_testing_a-proto_socks.o
-rw-r--r-- 1 sai sai   19680 Oct 29 14:55 src_or_libtor_testing_a-protover.o
-rw-r--r-- 1 sai sai   21072 Oct 29 14:55 src_or_libtor_testing_a-reasons.o
-rw-r--r-- 1 sai sai   88936 Oct 29 14:55 src_or_libtor_testing_a-relay.o
-rw-r--r-- 1 sai sai   31664 Oct 29 14:55 src_or_libtor_testing_a-rendcache.o
-rw-r--r-- 1 sai sai   40928 Oct 29 14:55 src_or_libtor_testing_a-rendclient.o
-rw-r--r-- 1 sai sai   31288 Oct 29 14:55 src_or_libtor_testing_a-rendcommon.o
-rw-r--r-- 1 sai sai   12584 Oct 29 14:55 src_or_libtor_testing_a-rendmid.o
-rw-r--r-- 1 sai sai  116152 Oct 29 14:55 src_or_libtor_testing_a-rendservice.o
-rw-r--r-- 1 sai sai   91088 Oct 29 14:55 src_or_libtor_testing_a-rephist.o
-rw-r--r-- 1 sai sai    5704 Oct 29 14:55 src_or_libtor_testing_a-replaycache.o
-rw-r--r-- 1 sai sai   42216 Oct 29 14:55 src_or_libtor_testing_a-routerkeys.o
-rw-r--r-- 1 sai sai  157392 Oct 29 14:55 src_or_libtor_testing_a-routerlist.o
-rw-r--r-- 1 sai sai  110992 Oct 29 14:55 src_or_libtor_testing_a-router.o
-rw-r--r-- 1 sai sai  193464 Oct 29 14:55 src_or_libtor_testing_a-routerparse.o
-rw-r--r-- 1 sai sai   16016 Oct 29 14:55 src_or_libtor_testing_a-routerset.o
-rw-r--r-- 1 sai sai   29952 Oct 29 14:55 src_or_libtor_testing_a-scheduler_kist.o
-rw-r--r-- 1 sai sai   21800 Oct 29 14:55 src_or_libtor_testing_a-scheduler.o
-rw-r--r-- 1 sai sai    6784 Oct 29 14:55 src_or_libtor_testing_a-scheduler_vanilla.o
-rw-r--r-- 1 sai sai   40424 Oct 29 14:55 src_or_libtor_testing_a-shared_random.o
-rw-r--r-- 1 sai sai   40104 Oct 29 14:55 src_or_libtor_testing_a-shared_random_state.o
-rw-r--r-- 1 sai sai   26032 Oct 29 14:55 src_or_libtor_testing_a-statefile.o
-rw-r--r-- 1 sai sai    7992 Oct 29 14:55 src_or_libtor_testing_a-status.o
-rw-r--r-- 1 sai sai   26272 Oct 29 14:55 src_or_libtor_testing_a-torcert.o
-rw-r--r-- 1 sai sai   49688 Oct 29 14:55 src_or_libtor_testing_a-transports.o
-rwxr-xr-x 1 sai sai 7231136 Oct 29 14:55 tor
-rw-r--r-- 1 sai sai   23505 Oct 19  2017 torcert.c
-rw-r--r-- 1 sai sai    4214 Oct 19  2017 torcert.h
-rw-r--r-- 1 sai sai   25936 Oct 29 14:55 torcert.o
-rw-r--r-- 1 sai sai    1004 Oct 19  2017 tor_main.c
-rw-r--r-- 1 sai sai    1608 Oct 29 14:55 tor_main.o

**Comment by robgjansen** [comment]
Can you show the output of `$ echo ${PATH}`? 

If the output does not contain `/home/sai/shadow/shadow-plugin-tor/build/tor/src/tools/` and `/home/sai/shadow/shadow-plugin-tor/build/tor/src/or/`, that is your problem. You need to set your $PATH variable correctly.

See for example [this stackoverflow question](https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix).

**Comment by keethu0519** [comment]
the path contains the value 
sai@sai-VirtualBox:~/mytor1$ /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sai/.shadow/bin:/home/sai/.shadow/bin:/home/sai/shadow/shadow-plugin-tor/build/tor/src/or:/home/sai/shadow/shadow-plugin-tor/build/tor/src/tools:/home/sai/shadow/shadow-plugin-tor/build/tor/src/or:/home/sai/shadow/shadow-plugin-tor/build/tor/src/tools:home/sai/shadow/shadow-plugin-tor/build/tor/src/tools

The path has the value specified but i am still getting the error please ensure 'tor' and 'tor-gencert' are in your 'PATH'
when i checked the folders i only see the gencert.c, gencert.o files but tor.c and tor.o doesnt exist as mentioned in the above comment.
sai@sai-VirtualBox:~/mytor1$ python ~/shadow/shadow-plugin-tor/tools/generate.py -p PATH --nauths 1 --nrelays 20 --nclients 200 --nservers 10 --fweb 0.90 --fbulk 0.10 --nperf50k 20 --nperf1m 10 --nperf5m 5 /home/sai/shadow-plugin-tor/tools/parsealexa.py /home/sai/2018-10-20-18-00-00-consensus  /home/sai/server-descriptors-2017-01 /home/sai/extra-infos-2017-01 /home/sai/clients.csv
[2018-10-30 09:48:20.599567] please ensure 'tor' and 'tor-gencert' are in your 'PATH'

**Comment by robgjansen** [comment]
Did you get this working? You might need to do:

```
cd /home/sai/shadow/shadow-plugin-tor/build/tor/
make all
```

to get Tor to build the gencert binary correctly?

**Comment by robgjansen** [comment]
I assume this is invalid or you got it working. Please comment if I'm wrong.

**Comment by robgjansen** [comment]
See shadow/shadow#680 for more details if you have this problem.
