### ISSUE TITLE
generate.py fails in getServers due to alexa

### ISSUE THREAD

**Issue by keethu0519** [shadow/shadow-plugin-tor#61]
```
$ python ~/shadow/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 20 --nclients 100 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 50 --nperf1m 25 --nperf5m 25 /home/sai/shadow-plugin-tor/tools/parsealexa.py /home/sai/2018-10-20-18-00-00-consensus /home/sai/2018-10-21-17-05-00-server-descriptors /home/sai/2018-10-21-17-05-00-extra-infos /home/sai/clients.csv
Traceback (most recent call last):
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 1132, in <module>
    main()
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 214, in main
    generate(args)
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 264, in generate
    servers = getServers(geoentries, args.alexa)
  File "/home/sai/shadow/shadow-plugin-tor/tools/generate.py", line 766, in getServers
    ip = parts[2]
IndexError: list index out of range
```

how do i fix this?

_Originally posted by @keethu0519 in https://github.com/shadow/shadow-plugin-tor/issues/59#issuecomment-432739217_

**Comment by robgjansen** [comment]
You passed in the incorrect argument for the alexa data. You should not pass in the script `/home/sai/shadow-plugin-tor/tools/parsealexa.py`.

As explained on [the wiki](https://github.com/shadow/shadow-plugin-tor/wiki#prepare-alexa-website-data), you first need to run the `parsealexa.py` script on the alexa data. The script will produce a file called `alexa-top-1000-ips.csv`, and this file should be passed in to the `generate.py` script.

The wiki explains this in detail and walks you through the process, please read carefully!
https://github.com/shadow/shadow-plugin-tor/wiki#generating-a-new-tor-network
