### ISSUE TITLE
can i write a program to call this simulator?

### ISSUE THREAD

**Issue by beastsam** [shadow/shadow-plugin-tor#67]
hi, I want to write a program which can used in tor network, so i want to know Whether can my program call this simulatoro or its API to do some test. if it works, where can i find some guide documentation? thank you

**Comment by robgjansen** [comment]
You can just write your application the same way you would if you were writing it to run in Linux, and then it should work in Shadow as well.

Here is a related question: shadow/shadow#678

This person wrote an example plugin that does something like you were asking:
https://github.com/shadow/shadow-plugin-extras/tree/master/tor-echo
