### ISSUE TITLE
./setup build problem

### ISSUE THREAD

**Issue by beastsam** [shadow/shadow-plugin-tor#68]
Hi, when I run ./setup build  ,i met a problem which is just like picture1 
![111](https://user-images.githubusercontent.com/41358375/53394226-885d1980-39d9-11e9-9cb5-2017df3409c6.png)

and the CmakeError.log is just like picture2
![error](https://user-images.githubusercontent.com/41358375/53394284-cb1ef180-39d9-11e9-85ca-04e8423f3f59.png)

and the CMakeOutput.log is as follow
[CMakeOutput.log](https://github.com/shadow/shadow-plugin-tor/files/2904191/CMakeOutput.log)

I'm not good at programming, is there someone who knows how to figure this problems?
Thank you very much :)

**Comment by jtracey** [comment]
Did you install [shadow](https://github.com/shadow/shadow) first?

**Comment by beastsam** [comment]
> Did you install [shadow](https://github.com/shadow/shadow) first?

sorry, i forgot that. but after i install shadow successfully, i still met this problem, the error is the same.

**Comment by beastsam** [comment]
> Did you install [shadow](https://github.com/shadow/shadow) first?

hi, i searched some ways to solved this problem, somebody said i should search the 'ShadowTools.cmake' 'RTConfig.cmake' and 'rt-config.cmake' these three files and add the path to my  PATH environment variable . 
first, i searched the 'ShadowTools.cmake' and copy that file to the /shadow-plugin-tor-master/cmake.
but i can't find the file 'RTConfig.cmake' and 'rt-config.cmake'. and i run the ./build again, the error about the shadowtools disappeard, but the another problem i still can't solve.
do you have some suggestions?
:)

**Comment by beastsam** [comment]
> Did you install [shadow](https://github.com/shadow/shadow) first?

hi, i think i found where the problem is , it happend in bulid plugin using cmake,
wen i run 'cmake ../.. -DTOR_VERSION_A=0 -DTOR_VERSION_B=2 -DTOR_VERSION_C=9 -DTOR_VERSION_D=11', the error appear, 
![image](https://user-images.githubusercontent.com/41358375/53641824-17349500-3c6b-11e9-85fa-ff9ebc7a456e.png)
so do you have an idea about how to fix this ? thank you

**Comment by nikBharti** [comment]
I was able to solve the issue just by coping all the file available in  /path/to/shadow-1.12.1/cmake/* to  /path/to/shadow-plugin-tor/cmake/
Try this it might solve the problem

**Comment by beastsam** [comment]
> I was able to solve the issue just by coping all the file available in /path/to/shadow-1.12.1/cmake/* to /path/to/shadow-plugin-tor/cmake/
> Try this it might solve the problem

thank you very much ,i will try it.
:)

**Comment by robgjansen** [comment]
Thank you @nikBharti !

After your message I noticed that indeed shadow-plugin-tor links some libraries but the plugin does not contain cmake search files to find those libraries. Sometimes your OS will include versions of these files if you install the right cmake-dev package, but sometimes they don't. When they are not included, we usually fall back on our own cmake files.

In this case, the one that is missing can be found in the base shadow directory:
https://github.com/shadow/shadow/blob/master/cmake/FindRT.cmake

I guess I should copy over those cmake files into the shadow-plugin-tor repo for all libraries that we depend on. Those include:

```
find_package(RT REQUIRED)
find_package(DL REQUIRED)
find_package(M REQUIRED)
find_package(OPENSSL REQUIRED)
find_package(EVENT2 REQUIRED)
find_package(GLIB REQUIRED)
find_package(LibLZMA)
```

**Comment by robgjansen** [comment]
> I guess I should copy over those cmake files into the shadow-plugin-tor repo for all libraries that we depend on.

Actually, no. If you have already installed Shadow correctly, then the cmake modules that you need should already exist in `~/.shadow/share/cmake/Modules/`

Can you please check to see if `FindRT.cmake` already exists in your `~/.shadow/share/cmake/Modules/` directory?

**Comment by ZWZfriso** [comment]
hi, I am working my graduation program designing in improving Tor's path selection. 
Could anyone tell me where I can acquire more tutorials about shadow with tor plug-in?

**Comment by robgjansen** [comment]
Your question is off-topic for this thread.

There is a tutorial on the wiki:
https://github.com/shadow/shadow-plugin-tor/wiki#tor-experimentation-and-analysis

That explains in detail how to run Tor experiments in Shadow. If you want anything specific to Tor configurations, like if you want to know how to change Tor so it uses different path selection algorithms, you should ask on one of the Tor project mailing lists:
https://lists.torproject.org/cgi-bin/mailman/listinfo
