### ISSUE TITLE
getRandomBytes not operating correctly

### ISSUE THREAD

**Issue by jdgeddes** [shadow/shadow-plugin-tor#7]
Currently the Tor plugin for shadow intercepts the call to the OpenSSL function RAND_bytes in `_shadowtorinterpose_getRandomBytes`.  The function fills in `buf` by calling `rand()` and copying the results into the buffer.  The issue is that `rand()` (which is intercepted by shadow) returns a value between 0 and 2^31 (which is RAND_MAX, the largest value for a signed integer), but the code that calls this expects the values to be between 0 and 2^32 (the largest value for an unsigned integer, or UINT_MAX).  Where this can really become a problem is in the `crypto_rand_double` function in Tor, which calls `RAND_bytes` passing it an unsigned int, and divides the result by UINT_MAX.  So while the function should return a double `0 <= d <= 1`, it actually returns `0 <= d <= 0.5`.

For now I have a workaround, instead of `guint r = rand()`, I have

```
gushort r1 = rand() & 0xFFFF;
gushort r2 = rand() & 0xFFFF;
guint r = (r1 << 16) | r2;
```

It fixes the issue, but might not be the most elegant solution.  I haven't looked into it fully, but it may be the case that the shadow Tor plugin doesn't need to intercept the function at all, to just leave it to shadow to intercept the proper random functions.  One guess is that originally it was getting the random values from reading in data from `/dev/random` which we didn't use to intercept.  Now that we do, it might not be necessary to intercept the RAND_bytes function, but can't be sure.

**Comment by robgjansen** [comment]
Good catch! We should definitely run the OpenSSL `RAND_bytes` function through GDB without intercepting it to see if one of the other underlying random functions that shadow handles properly get called. If not, I'm fine with accepting your fix above.

**Comment by robgjansen** [comment]
@jdgeddes would you be able to run this through gdb with the new v1.10.0 release, and still if the issue is still here?

**Comment by robgjansen** [comment]
@jdgeddes do you have any information about this bug for the latest Shadow? I'm wondering if it is still a problem. Thanks!
