### ISSUE TITLE
The minimal example errors about libshadow-plugin-tor.so 、 max_map_count and core dump

### ISSUE THREAD

**Issue by beastsam** [shadow/shadow-plugin-tor#71]
Hi , recently, I met a problem. I installed the shadow and shadow-plugin-tor successfully. But when i run the minimal example for test, the errors such as the picture.
![image](https://user-images.githubusercontent.com/41358375/55327247-3cabfd00-54bc-11e9-98a8-4a54729a6508.png)
As you can see, I checked the file and the max_map_count. The filepath is right and the Permission is ok, the max_map_count is also the guide number.

Later, I checked the shadow.log.
there is no errors in the shadow.log, but there some warnings, such as 
![image](https://user-images.githubusercontent.com/41358375/55329192-96162b00-54c0-11e9-86bc-519877ad53ec.png)

[shadow.log](https://github.com/shadow/shadow-plugin-tor/files/3029413/shadow.log)

The corefile picture is as follow.
![2](https://user-images.githubusercontent.com/41358375/55328947-1b4d1000-54c0-11e9-8f6f-bbf3b9e25a13.png)

My system is CentOS Linux release 7.5.1804
Is rhere someone met this problem?
If you know how to fix tihs, please tell me and thank you very much.

**Comment by robgjansen** [comment]
Shadow is getting an error when it is trying to open a file. You increased the `max_map_count`, but did you also increase the [open file limits](https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-open-files)? Please post the output of

```
sysctl fs.nr_open
sysctl fs.file-max
ulimit -n
```

**Comment by beastsam** [comment]
> Shadow is getting an error when it is trying to open a file. You increased the `max_map_count`, but did you also increase the [open file limits](https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-open-files)? Please post the output of
> 
> ```
> sysctl fs.nr_open
> sysctl fs.file-max
> ulimit -n
> ```



> Shadow is getting an error when it is trying to open a file. You increased the `max_map_count`, but did you also increase the [open file limits](https://github.com/shadow/shadow/wiki/1.1-Shadow#number-of-open-files)? Please post the output of
> 
> ```
> sysctl fs.nr_open
> sysctl fs.file-max
> ulimit -n
> ```

Thank you very much. I found the problem. I didn't change my limits.conf file correctly.Now it's ok.
:)
