### ISSUE TITLE
Segmentation fault when run 200 nodes

### ISSUE THREAD

**Issue by mitik2** [shadow/shadow-plugin-tor#73]
When I tried to run 100 nodes, Shadow was able to complete the simulation.
When I increased the number of nodes, I received the following error message:

> ** Starting Shadow v1.13.0-53-ga31f3e21 2019-04-22 (built 2019-04-27) with GLib v2.56.3 and IGraph v0.7.1
/home/mitik/workspace/shadow/src/external/elf-loader/vdl-map.c:805:vdl_file_map_single: Could not open ro target file: /home/mitik/.shadow/bin/gossip
/home/mitik/workspace/shadow/src/external/elf-loader/vdl-map.c:979, vdl_file_map_single_maybe, Attempted mapping failed. Try adjusting your system's max_map_count.
Error: signal 11:

I tried to adjust the max_map_count to the same value that was recommended in the wiki, but I keep getting the mentioned above error.

**Comment by robgjansen** [comment]
You need to change both the system and the user file limits, as is also described on the wiki:
https://github.com/shadow/shadow/wiki/1.1-Shadow#system-configs-and-limits

Did you change the file limits?

**Comment by mitik2** [comment]
I did, but apparently, it had no effect. I had to follow this answer: 

[https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu/1200818#1200818](url).

It seems to solve the issue. Thanks!
