### ISSUE TITLE
Analyze not giving empty output

### ISSUE THREAD

**Issue by ivosousaa** [shadow/shadow-plugin-tor#75]
So basically we try to run analyze parse it gives us empty output even though our experiment runs with no issues and our shadow.log file, which we use with the analyze parse tool has the expected info.

Someone else having this problem?

**Comment by robgjansen** [comment]
Can you please tell us which exact commands you are running that are producing an unexpected result? Are you running the `parse-shadow.py` or the `parse-torctl.py` script? And the `plot-shadow.py` script?

Note that if you are trying to parse `tgen` traffic generator output, you should follow the instructions at the new tgen repository here:
https://github.com/shadow/tgen/blob/master/doc/Tools-Setup.md

**Comment by ivosousaa** [comment]
Oh ok so we tried to use analyze parse shadow.log, this produced the empty results. Then we did use parse-torctl.py on the hosts folder, this produced a json file, which did work as expected but then we can't plot it with any tool, what would you suggest for that?

Also we did also use parse-shadow.py and the plot-shadow.py which is also working correctly, is there any documentation to help us understand the graphs generated btw? They seem to be about the network performance in general if we're correct.

**Comment by robgjansen** [comment]
The `tools/analyze.py` script is old and is no longer supported.

There is a tutorial for running Shadow experiments here:
https://github.com/shadow/shadow/wiki/2-Getting-Started-Tutorial

Then, if you run Tor experiments, you have one more data source - the Tor log files.
https://github.com/shadow/shadow-plugin-tor/wiki#tor-experimentation-and-analysis

So after you run a Tor experiment and get a `shadow.data` directory containing results from your experiment, you would do something like the following:

```
python ~/shadow/src/tools/parse-shadow.py shadow.log
python ~/shadow-plugin-tor/tools/parse-torctl.py shadow.data/hosts
python ~/shadow/src/tools/plot-shadow.py --data . "test"
```
So first you parse the shadow log file, then you parse the tor log files, then `plot-shadow.py` should plot both of them.

TGen results are separated. You can also parse and plot the TGen output using the `tgentools` program from the TGen repo. This page describes how to get started.
https://github.com/shadow/tgen/blob/master/doc/Tools-Setup.md

Yes, the focus of these scripts is on performance. If you want other details, you'll have to look through the log files and write your own parsing and plotting scripts to extract whatever details you want to analyze. Of course you can use or extend our scripts as a starting point.

Hope that helps!

**Comment by ivosousaa** [comment]
Ohh ok okk, good to know. Thanks we get it now! 

We we're actually more interested in having a graph with sent and received bytes so we could simulate a traffic correlation attack, but as I understand we would need to generate our own graphs then, we did find that the parse-torctl.py output is what we're probably looking after to build these graphs, are we thinking correcly? Also, if you do have any tips, they would be welocome.

Thanks a bunch for your help and great tool btw.

**Comment by robgjansen** [comment]
Yes, the parse-torctl.py output gives you per-second Tor throughput for each Tor node, and this may be useful for analysis of end-to-end correlation. But of course it depends on the exact attack scenario you are considering.

Good luck and have fun :)
