### ISSUE TITLE
Installation instructions have errors

### ISSUE THREAD

**Issue by ndanger000** [shadow/shadow-plugin-tor#8]
The installation instructions suggest the following to clone shadow-plugin-tor

git clone https://github.com/shadow/shadow-plugin-tor.git -b release

There is no release branch for this project.

**Comment by robgjansen** [comment]
Good find :) I was planning to add a release branch to match shadow/shadow releases, but then I also considered simply removing the release branch in shadow/shadow in favor of good old master. I guess I'll create the release branch for now.

**Comment by robgjansen** [comment]
New release branches were just pushed for shadow/shadow-plugin-tor and shadow/shadow-plugin-bitcoin.
