### ISSUE TITLE
～/.shadow/bin/tgen is not valid path

### ISSUE THREAD

**Issue by GitZinger** [shadow/shadow-plugin-tor#99]
So
I install the shadow, TGen, Plug-in-Tor, following the book step by step.
and tried to run 
`shadow shadow.config.xml > shadow.log`
according to the https://github.com/shadow/shadow-plugin-tor/wiki
it prompts 
`～/.shadow/bin/tgen is not valid path`
for the TGen I followed the https://github.com/shadow/tgen   (README.md)
there is no specific specification for the TGen to be installed in the **～/.shadow/bin/** folder, and I tried to change the TGen path in **shadow.config.xml** in the Tor/resource folder, still it does not work, please help what else I should do to make these things working together ?

**Comment by jtracey** [comment]
If you want to run TGen in Shadow, you should be following [Shadow's instructions](https://github.com/shadow/shadow/blob/master/docs/1.1-Shadow.md#tgen-setup), not TGen's. Specifically, you need to point the install prefix at the `~/.shadow` directory, not `~/.local`.

**Comment by GitZinger** [comment]
> If you want to run TGen in Shadow, you should be following [Shadow's instructions](https://github.com/shadow/shadow/blob/master/docs/1.1-Shadow.md#tgen-setup), not TGen's. Specifically, you need to point the install prefix at the `~/.shadow` directory, not `~/.local`.
thank you 
I tried 
`DCMAKE_INSTALL_PREFIX=/home/$USER/.shadow`
but still it does not work.
any change I should make in the **shadow.config.xml** file in the Tor/resource folder? 
currently in the `~/.shadow/bin` folder there is no any tgen folder or files.

**Comment by jtracey** [comment]
You need to run the cmake command to configure, `make` to build, then `make install` to install to that directory. If you have problems, try removing the build directory and start over.

**Comment by GitZinger** [comment]
> You need to run the cmake command to configure, `make` to build, then `make install` to install to that directory. If you have problems, try removing the build directory and start over.



ah thank you so much! I am not being myself today. figured it out. but I encounter another error.
any chance you could help me here? I really appreciate it!
[shadow.log](https://github.com/shadow/shadow-plugin-tor/files/4467336/shadow.log)

**Comment by jtracey** [comment]
That's likely because of a similar issue to https://github.com/shadow/shadow/issues/742; I don't think the examples in shadow-plugin-tor have been updated to the new TGen version.

**Comment by robgjansen** [comment]
I'm looking into this now.

**Comment by robgjansen** [comment]
Opened GH-100 for the config issue, where we need to update the minimal and toy examples. The original issue reported here, i.e., the install location of tgen, has been fixed so I am closing this now.
